id: 9242876a-41c4-42f8-96f8-ac92d6025406
title: Settings
data:
  site_name: 'Robert van Steen'
  social:
    -
      name: Github
      url: 'https://github.com/robertvansteen'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:mail@robertvansteen.com'
      icon: site/social-icons/email.svg
